@startuml
title Блок-схема платёжного Telegram-бота

start

:/start;
:Вывод информации о программе;
:Кнопка "Скачать";

if (Пользователь нажал кнопку\n«Скачать»?") then (Да)

  :Отправить сообщение с инструкцией по установке\nи использованию программы;
  :Кнопка «С инструкцией ознакомлен»;

  if (Пользователь нажал кнопку\n«С инструкцией ознакомлен») then (Да)

    :Переход к платёжной системе Telegram;

    if (Платёж успешен?) then (Да)
      :Сгенерировать ключ;
      :Отправить ключ и ссылку на скачивание программы;
    else (Нет)
      :Показать ошибку и предложить\nповторить попытку;
    endif

  else (Нет)
    :Режим ожидания нажатия кнопки;
  endif

else (Нет)
  :Режим ожидания нажатия кнопки;
endif

stop
@enduml